### PR TITLE
Feat/Refactor: Add missing error messages and fix file descriptor leak

### LINKED ISSUE #93: Missing error messages
Right now, while reading the .rt file, if an error occurs the application will exit with an error code and without a descriptive message like the pdf asks for.

Also, the code for the error messages can see improvements.

### PR DESCRIPTION
**Pull request by Leofariasrj25**
Okay, this one changed more things than I expected:

* Most of the error messages are now bound to an enum type, this was done in order to make the code more expressive and direct.

* The second advantage of using enums for error codes is that now most of the messages are now centralized in a table inside get_error_msg

* There are two major types of errors: scene opening errors or scene parsing/loading errors.
   * for the first kind of error the error msg will have a short description of the error and then show the filename
   * for the second kind, parsing/loading, the error message will try to be as descriptive as possible and show the current line number where the error occurred.
   
 * Also took the time and implemented scene_fd closing logic. now the scene_fd is stored inside the t_info struct and the `destroy_scene` also receives the scene_fd. if for some reason the fd cannot be closed, an appropriate error msg will be displayed
 
 * All of the tests are passing and minor changes were made to accommodate the refactor.

### CODE REVIEW

File: sources/input/error.c [hunk 1]
```diff
@@ -6,36 +6,56 @@
...
+	error_msg[err_file_type] = "the current file is not a .rt file";
+	error_msg[err_file_fmt] = "the file formatting is invalid";
+	error_msg[err_file_perm] = "could not read file: permission denied";
+	error_msg[err_file_not_found] = "file not found";
+	error_msg[err_obj_attr_fmt] = "invalid format for object's attribute";
+	error_msg[err_obj_attr_value] = "invalid value for object's attribute";
+	error_msg[err_obj_attr_miss] = "wrong attr size in object declaration";
+	error_msg[err_obj_dup] = "multiple unique objects [light, camera, a_light]";
+	error_msg[err_obj_invalid] = "invalid object";
+	return (error_msg[error_code]);
```
Comment (gabrielclcardoso) [inline sources/input/error.c]: Aren't you returning a pointer to the stack memory of the function? Wouldn't this space in memory hold unpredictable values after the function returns?

File: sources/input/error.c [hunk 2]
```diff
@@ -6,36 +6,56 @@
...
+void	print_scene_error(int err_code, int line_number)
 {
-	ft_putstr_fd("ERROR: file not found: ", STDERR_FILENO);
-	ft_putendl_fd(filename, STDERR_FILENO);
+	char	*nbr_str;
+
+	nbr_str = ft_itoa(line_number);
+	print_error_msg(err_code);
+	ft_putstr_fd(": line ", STDERR_FILENO);
+	ft_putendl_fd(nbr_str, STDERR_FILENO);
```
Comment (gabrielclcardoso) [inline sources/input/error.c]: You could use ft_putnbr_fd, this way you wouldn't have to allocate and free memory. It works either way though.

**Review by gabrielclcardoso — CHANGES_REQUESTED** [review]
All good apart from the function get_error message, which I belive returns a pointer to an invalid part of memory.

File: sources/input/error.c (hunk 1 above)
Comment (Leofariasrj25) [reply sources/input/error.c]: About that, I did some research and this is a valid way to return string literals

https://www.geeksforgeeks.org/storage-for-strings-in-c/

Usually string literals are stored in the data segment of the program's memory, apart from the stack and heap segments.

If we do

`char name[] = "Leo";
and then return (name)`
then that will get us in trouble because name will be created on the stack like any other local/auto variable because it's an array.

But 

`char *name = "Leo";
return (name); `
Is ok because this is a pointer.

I also went to ChatGPT and got the same answer:

> In the C programming language, string literals like "Leonardo" are typically stored in a read-only section of memory, such as the program's code segment or a read-only data segment.
> When you declare a character pointer variable like char *name = "Leonardo";, the compiler will typically allocate a block of memory to hold the string literal "Leonardo", and then initialize the pointer variable name to point to the first character of that memory block. The memory block containing the string literal is usually stored in a read-only section of memory to prevent accidental modifications of the string.
> The exact location where the string literal is stored may depend on the compiler, operating system, and platform you are using. However, it is typically stored in a memory location that is separate from the stack and heap, which are used for storing local variables and dynamically allocated memory, respectively.

But, I do think we could just strdup those strings when returning them and free after their use just to be extra cautious.

File: sources/input/error.c (hunk 2 above)
Comment (Leofariasrj25) [reply sources/input/error.c]: Oh, I did not remember about this one. Thanks, I'll change the code to use it.
